pipeline {
    agent any
         stages {
           stage('Compile and Clean') {
                steps {
                       sh "mvn clean compile"
                       }
                }


            stage('deploy') {
                steps {
                 sh "mvn package"
                 }
                  }


        stage('Build Docker image'){
            steps {

                sh 'docker build -t  revature-cps-rest ./cps-rest'

            }
        }


        stage('Backend Deploy'){
            steps {
                sh 'docker run -d -p  2021:2021 revature-cps-rest'
            }
        }
    }
}
