pipeline {
    agent any
         stages {
            stage('Compile and Deploy') {
                steps {
                       sh "mvn clean package"
                       }
                }



        stage('Build Docker image'){
            steps {

                sh 'docker build -t  revature-cps-backend ./cps-backend'
            }
        }


        stage('Backend Deploy'){
            steps {
                sh 'docker run -d -p  2021:2021 revature-cps-backend'
            }
        }
    }
