pipeline {
    agent any
    stages {
        stage('build-and-deploy') {
            steps {

                sh 'docker build -t revature-cps ./cps-fronend'
                sh 'docker run -d -p 5001:5001 cps'

            }
        }
    }
}
